version: '2'
services:
  database:
    container_name: db
    restart: always
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
  java:
    image: vehiculos
    links:
     - "database"